export const SHORT_ID_LENGTH = 8;
export const SHORT_ID_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};

export const REDIRECT_CACHE_TTL_SECONDS = 86400;

export const RATE_LIMIT_WINDOW_MS = 60 * 1000;
export const RATE_LIMIT_MAX_CREATE = 10;
export const RATE_LIMIT_MAX_REDIRECT = 100;
export const RATE_LIMIT_MAX_ANALYTICS = 30;
